CREATE TABLE question
(
    QuestionID       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    QuestionText     TEXT                                    NOT NULL,
    QuestGroupID     BIGINT                                  NOT NULL,
    CorrectComment   TEXT,
    IncorrectComment TEXT,
    QuestTypeID      BIGINT                                  NOT NULL,
    Score            FLOAT4 DEFAULT '1'                      NOT NULL,
    IsShuffleAnswers BOOLEAN                                 NOT NULL,
    IsCount          BOOLEAN                                 NOT NULL,
    CONSTRAINT Question_pkey PRIMARY KEY (QuestionID)
);

CREATE TABLE test
(
    TestID             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Name               TEXT                                    NOT NULL,
    Description        TEXT,
    DisciplineID       BIGINT,
    Link               TEXT,
    IsShuffleQuestions BOOLEAN DEFAULT TRUE                    NOT NULL,
    CONSTRAINT Test_pkey PRIMARY KEY (TestID)
);

CREATE TABLE flyway_schema_history
(
    installed_rank INTEGER       NOT NULL,
    version        VARCHAR(50),
    description    VARCHAR(200)  NOT NULL,
    type           VARCHAR(20)   NOT NULL,
    script         VARCHAR(1000) NOT NULL,
    checksum       INTEGER,
    installed_by   VARCHAR(100)  NOT NULL,
    installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    execution_time INTEGER       NOT NULL,
    success        BOOLEAN       NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

CREATE TABLE answer
(
    AnswerID    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    AnswerValue TEXT                                    NOT NULL,
    QuestionID  BIGINT                                  NOT NULL,
    IsRight     BOOLEAN                                 NOT NULL,
    CONSTRAINT Answer_pkey PRIMARY KEY (AnswerID)
);

CREATE TABLE discipline
(
    DisciplineID   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DisciplineName TEXT                                    NOT NULL,
    CONSTRAINT Discipline_pkey PRIMARY KEY (DisciplineID)
);

CREATE TABLE questBase
(
    QuestBaseID   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DisciplineID  BIGINT                                  NOT NULL,
    QuestBaseName TEXT                                    NOT NULL,
    CONSTRAINT QuestBase_pkey PRIMARY KEY (QuestBaseID)
);

CREATE TABLE questGroup
(
    QuestGroupID   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    QuestBaseID    BIGINT                                  NOT NULL,
    QuestGroupName TEXT                                    NOT NULL,
    CONSTRAINT QuestGroup_pkey PRIMARY KEY (QuestGroupID)
);

CREATE TABLE questType
(
    QuestTypeID   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    QuestTypeName TEXT                                    NOT NULL,
    CONSTRAINT QuestType_pkey PRIMARY KEY (QuestTypeID)
);

CREATE TABLE role
(
    RoleID   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    RoleName TEXT                                    NOT NULL,
    CONSTRAINT Role_pkey PRIMARY KEY (RoleID)
);

CREATE TABLE studentsGroup
(
    StudentsGroupID   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    StudentsGroupName TEXT                                    NOT NULL,
    CONSTRAINT StudentsGroup_pkey PRIMARY KEY (StudentsGroupID)
);

CREATE TABLE testQuests
(
    TestQuestsID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    QuestionID   BIGINT                                  NOT NULL,
    TestID       BIGINT                                  NOT NULL,
    CONSTRAINT TestQuests_pkey PRIMARY KEY (TestQuestsID)
);

CREATE TABLE testResult
(
    TestResultID           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CorrectPercent         TEXT,
    SkippedPercent         TEXT,
    TestID                 BIGINT                                  NOT NULL,
    UserID                 BIGINT                                  NOT NULL,
    TestResultUserAnswerID BIGINT                                  NOT NULL,
    CONSTRAINT TestResult_pkey PRIMARY KEY (TestResultID)
);

CREATE TABLE testResultUserAnswer
(
    TestResultUserAnswerID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    UserAnswerID           BIGINT                                  NOT NULL,
    TestResultID           BIGINT                                  NOT NULL,
    CONSTRAINT TestResultUserAnswer_pkey PRIMARY KEY (TestResultUserAnswerID)
);

CREATE TABLE university
(
    UniversityID   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    UniversityName TEXT                                    NOT NULL,
    CONSTRAINT University_pkey PRIMARY KEY (UniversityID)
);

CREATE TABLE "user"
(
    UserID          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    FullName        TEXT                                    NOT NULL,
    Email           TEXT,
    Password        TEXT,
    PasswordSalt    TEXT,
    UniversityID    BIGINT,
    TelegramLogin   TEXT,
    TelegramID      TEXT,
    PhoneNumber     TEXT,
    RoleID          BIGINT                                  NOT NULL,
    StudentsGroupID BIGINT,
    CONSTRAINT User_pkey PRIMARY KEY (UserID)
);

CREATE TABLE userAnswer
(
    UserAnswerID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    QuestionID   BIGINT                                  NOT NULL,
    AnswerID     BIGINT                                  NOT NULL,
    UserAnswer   TEXT,
    Timestamp    TIMESTAMP WITHOUT TIME ZONE,
    IsSkipped    BOOLEAN                                 NOT NULL,
    IsCorrect    BOOLEAN                                 NOT NULL,
    CONSTRAINT UserAnswer_pkey PRIMARY KEY (UserAnswerID)
);

ALTER TABLE userAnswer
    ADD CONSTRAINT AnswerID FOREIGN KEY (AnswerID) REFERENCES answer (AnswerID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE test
    ADD CONSTRAINT DisciplineID FOREIGN KEY (DisciplineID) REFERENCES discipline (DisciplineID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE test
    ADD CONSTRAINT DisciplineID FOREIGN KEY (DisciplineID) REFERENCES discipline (DisciplineID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE questGroup
    ADD CONSTRAINT QuestBaseID FOREIGN KEY (QuestBaseID) REFERENCES questBase (QuestBaseID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE question
    ADD CONSTRAINT QuestGroupID FOREIGN KEY (QuestGroupID) REFERENCES questGroup (QuestGroupID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE question
    ADD CONSTRAINT QuestTypeID FOREIGN KEY (QuestTypeID) REFERENCES questType (QuestTypeID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE userAnswer
    ADD CONSTRAINT QuestionID FOREIGN KEY (QuestionID) REFERENCES question (QuestionID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE userAnswer
    ADD CONSTRAINT QuestionID FOREIGN KEY (QuestionID) REFERENCES question (QuestionID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE userAnswer
    ADD CONSTRAINT QuestionID FOREIGN KEY (QuestionID) REFERENCES question (QuestionID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user"
    ADD CONSTRAINT RoleID FOREIGN KEY (RoleID) REFERENCES role (RoleID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user"
    ADD CONSTRAINT StudentsGroupID FOREIGN KEY (StudentsGroupID) REFERENCES studentsGroup (StudentsGroupID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE testResult
    ADD CONSTRAINT TestID FOREIGN KEY (TestID) REFERENCES test (TestID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE testResult
    ADD CONSTRAINT TestID FOREIGN KEY (TestID) REFERENCES test (TestID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE testResultUserAnswer
    ADD CONSTRAINT TestResultID FOREIGN KEY (TestResultID) REFERENCES testResult (TestResultID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE testResult
    ADD CONSTRAINT TestResultUserAnswerID FOREIGN KEY (TestResultUserAnswerID) REFERENCES testResultUserAnswer (TestResultUserAnswerID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user"
    ADD CONSTRAINT UniversityID FOREIGN KEY (UniversityID) REFERENCES university (UniversityID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE testResultUserAnswer
    ADD CONSTRAINT UserAnswerID FOREIGN KEY (UserAnswerID) REFERENCES userAnswer (UserAnswerID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE testResult
    ADD CONSTRAINT UserID FOREIGN KEY (UserID) REFERENCES "user" (UserID) ON UPDATE NO ACTION ON DELETE NO ACTION;