CREATE TABLE flyway_schema_history
(
    installed_rank INTEGER       NOT NULL,
    version        VARCHAR(50),
    description    VARCHAR(200)  NOT NULL,
    type           VARCHAR(20)   NOT NULL,
    script         VARCHAR(1000) NOT NULL,
    checksum       INTEGER,
    installed_by   VARCHAR(100)  NOT NULL,
    installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    execution_time INTEGER       NOT NULL,
    success        BOOLEAN       NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE answer
(
    AnswerID    BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    AnswerValue TEXT                                                   NOT NULL,
    IsRight     BOOLEAN                                                NOT NULL,
    QuestionID  BIGINT                                                 NOT NULL,
    CONSTRAINT answer_pkey PRIMARY KEY (AnswerID)
);

CREATE TABLE discipline
(
    DisciplineID   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    DisciplineName TEXT                                                   NOT NULL,
    CONSTRAINT discipline_pkey PRIMARY KEY (DisciplineID)
);

CREATE TABLE questBaseService
(
    QuestBaseID   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    QuestBaseName TEXT                                                   NOT NULL,
    DisciplineID  BIGINT                                                 NOT NULL,
    CONSTRAINT questBaseService_pkey PRIMARY KEY (QuestBaseID)
);

CREATE TABLE questGroup
(
    QuestGroupID   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    QuestGroupName TEXT                                                   NOT NULL,
    QuestBaseID    BIGINT                                                 NOT NULL,
    CONSTRAINT questGroup_pkey PRIMARY KEY (QuestGroupID)
);

CREATE TABLE questType
(
    QuestTypeID   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    QuestTypeName TEXT                                                   NOT NULL,
    CONSTRAINT questType_pkey PRIMARY KEY (QuestTypeID)
);

CREATE TABLE question
(
    QuestionID       BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    CorrectComment   TEXT,
    IncorrectComment TEXT,
    IsCount          BOOLEAN                                                NOT NULL,
    IsShuffleAnswers BOOLEAN                                                NOT NULL,
    QuestionText     TEXT                                                   NOT NULL,
    Score            FLOAT4                                                 NOT NULL,
    QuestGroupID     BIGINT                                                 NOT NULL,
    QuestTypeID      BIGINT                                                 NOT NULL,
    CONSTRAINT question_pkey PRIMARY KEY (QuestionID)
);

CREATE TABLE role
(
    RoleID   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL,
    RoleName TEXT                                                   NOT NULL,
    CONSTRAINT role_pkey PRIMARY KEY (RoleID)
);

CREATE TABLE studentsGroup
(
    StudentsGroupID   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    StudentsGroupName TEXT                                                   NOT NULL,
    CONSTRAINT studentsGroup_pkey PRIMARY KEY (StudentsGroupID)
);

CREATE TABLE test
(
    TestID             BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    Description        TEXT,
    IsShuffleQuestions BOOLEAN                                                NOT NULL,
    Link               TEXT,
    Name               TEXT                                                   NOT NULL,
    DisciplineID       BIGINT,
    CONSTRAINT test_pkey PRIMARY KEY (TestID)
);

CREATE TABLE testQuests
(
    TestQuestsID BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    QuestionID   BIGINT                                                 NOT NULL,
    TestID       BIGINT                                                 NOT NULL,
    CONSTRAINT testQuests_pkey PRIMARY KEY (TestQuestsID)
);

CREATE TABLE testResult
(
    TestResultID   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 4) NOT NULL,
    CorrectPercent TEXT,
    SkippedPercent TEXT,
    TestID         BIGINT                                                 NOT NULL,
    UserID         BIGINT                                                 NOT NULL,
    CONSTRAINT testResult_pkey PRIMARY KEY (TestResultID)
);

CREATE TABLE testResultUserAnswerService
(
    TestResultUserAnswerID BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 6) NOT NULL,
    TestResultID           BIGINT                                                 NOT NULL,
    UserAnswerID           BIGINT                                                 NOT NULL,
    CONSTRAINT testResultUserAnswerService_pkey PRIMARY KEY (TestResultUserAnswerID)
);

CREATE TABLE university
(
    UniversityID   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 3) NOT NULL,
    UniversityName TEXT                                                   NOT NULL,
    CONSTRAINT university_pkey PRIMARY KEY (UniversityID)
);

CREATE TABLE "user"
(
    UserID          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL,
    Email           TEXT,
    FullName        TEXT                                                   NOT NULL,
    Password        TEXT,
    PasswordSalt    TEXT,
    PhoneNumber     TEXT,
    TelegramID      TEXT,
    TelegramLogin   TEXT,
    RoleID          BIGINT                                                 NOT NULL,
    StudentsGroupID BIGINT,
    UniversityID    BIGINT,
    CONSTRAINT user_pkey PRIMARY KEY (UserID)
);

CREATE TABLE userAnswer
(
    UserAnswerID BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    IsCorrect    BOOLEAN                                                NOT NULL,
    IsSkipped    BOOLEAN                                                NOT NULL,
    Timestamp    TIMESTAMP WITH TIME ZONE,
    UserAnswer   TEXT,
    AnswerID     BIGINT                                                 NOT NULL,
    QuestionID   BIGINT                                                 NOT NULL,
    CONSTRAINT userAnswer_pkey PRIMARY KEY (UserAnswerID)
);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

ALTER TABLE testQuests
    ADD CONSTRAINT fk1kvfuhjtyr5qj5967bhcj307v FOREIGN KEY (TestID) REFERENCES test (TestID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE questGroup
    ADD CONSTRAINT fk1tukr7g3gsqfq3j5i3p700y62 FOREIGN KEY (QuestBaseID) REFERENCES questBaseService (QuestBaseID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE userAnswer
    ADD CONSTRAINT fk4vajtdee4uvqaya9uj76hajqf FOREIGN KEY (AnswerID) REFERENCES answer (AnswerID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE userAnswer
    ADD CONSTRAINT fk692xfyw72ge4076hc253xke9n FOREIGN KEY (QuestionID) REFERENCES question (QuestionID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE question
    ADD CONSTRAINT fk75bq1idh4c78i18231i5eycab FOREIGN KEY (QuestGroupID) REFERENCES questGroup (QuestGroupID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE answer
    ADD CONSTRAINT fk8aohnhrvn39ku8ytqwbmt79o1 FOREIGN KEY (QuestionID) REFERENCES question (QuestionID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE testResultUserAnswerService
    ADD CONSTRAINT fkc5gf14f8aujvrf5wcq2pc709j FOREIGN KEY (UserAnswerID) REFERENCES userAnswer (UserAnswerID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE testResult
    ADD CONSTRAINT fkcntsuu7c03fvcfh24ufqew2se FOREIGN KEY (UserID) REFERENCES "user" (UserID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user"
    ADD CONSTRAINT fkex6fcc1uranhmyrygecp2b5fw FOREIGN KEY (RoleID) REFERENCES role (RoleID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE testQuests
    ADD CONSTRAINT fkfk9f1443aq7yotrgagw7wv59a FOREIGN KEY (QuestionID) REFERENCES question (QuestionID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE questBaseService
    ADD CONSTRAINT fkh9tn3ks4rhwg1o7mrjbon2vvb FOREIGN KEY (DisciplineID) REFERENCES discipline (DisciplineID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE question
    ADD CONSTRAINT fkjd96qdo6aasu42iuyakuaxjgq FOREIGN KEY (QuestTypeID) REFERENCES questType (QuestTypeID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user"
    ADD CONSTRAINT fkkrjvmwo4ny68nmyqd0jblr222 FOREIGN KEY (StudentsGroupID) REFERENCES studentsGroup (StudentsGroupID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user"
    ADD CONSTRAINT fklf176gqoddf39vedjlex6k6tp FOREIGN KEY (UniversityID) REFERENCES university (UniversityID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE testResult
    ADD CONSTRAINT fkmqs39c5e3h0g9f10ecga5sjbs FOREIGN KEY (TestID) REFERENCES test (TestID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE testResultUserAnswerService
    ADD CONSTRAINT fkpdxuh4gssjna3th8by3fs7hu2 FOREIGN KEY (TestResultID) REFERENCES testResult (TestResultID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE test
    ADD CONSTRAINT fksor8x91wn8c24k4a7a795bcn1 FOREIGN KEY (DisciplineID) REFERENCES discipline (DisciplineID) ON UPDATE NO ACTION ON DELETE NO ACTION;